version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Challenge
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data: